<script>
  /*
  Pending:
  Resolve: thren()
  Reject: catch()
  */

  let myPromise = new Promise(function (resolve, reject) {
    let success = true;

    if (success) {
      resolve("First step complete.");
    } else {
      reject("Something went wrong.")
    }
  });
  myPromise.then(function (result) {
    console.log(result);
    return "Next step complete."; // Returns a new promise.
  }).then(function (nextResult) {
    console.log(nextResult); // Output: "Next step complete."
  }).catch(function (error) {
    console.log(erroe); // Handles any error in the chain.
  });

</script>